require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'singhamarket' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  target 'singhamarketTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported

        if target.name == 'RNExitApp'
          header_search_paths = build_config.build_settings['HEADER_SEARCH_PATHS']
          header_search_paths = ['$(inherited)'] if header_search_paths.nil?
          header_search_paths = [header_search_paths] if header_search_paths.is_a?(String)
          generated_ios_path = '"$(PODS_ROOT)/../build/generated/ios"'
          header_search_paths << generated_ios_path unless header_search_paths.include?(generated_ios_path)
          build_config.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths
        end

        next unless target.name == 'GoogleDataTransport'

        other_cflags = build_config.build_settings['OTHER_CFLAGS']
        other_cflags = ['$(inherited)'] if other_cflags.nil?
        other_cflags = [other_cflags] if other_cflags.is_a?(String)
        other_cflags << '-Wno-strict-prototypes' unless other_cflags.include?('-Wno-strict-prototypes')
        build_config.build_settings['OTHER_CFLAGS'] = other_cflags
        build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      end
    end

    gdt_clock_path = File.join(
      installer.sandbox.root,
      'GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORClock.m'
    )
    if File.exist?(gdt_clock_path)
      gdt_clock_source = File.read(gdt_clock_path)
      gdt_clock_source.gsub!('KernelBootTimeInNanoseconds(void);',
                             'KernelBootTimeInNanoseconds();')
      gdt_clock_source.gsub!('UptimeInNanoseconds(void);',
                             'UptimeInNanoseconds();')
      gdt_clock_source.gsub!(/static int64_t KernelBootTimeInNanoseconds\(\) \{/,
                             'static int64_t KernelBootTimeInNanoseconds(void) {')
      gdt_clock_source.gsub!(/static int64_t UptimeInNanoseconds\(\) \{/,
                             'static int64_t UptimeInNanoseconds(void) {')
      File.chmod(0o644, gdt_clock_path)
      File.write(gdt_clock_path, gdt_clock_source)
    end

    [
      'FirebaseMessaging/FirebaseMessaging/Sources/Protos/GtalkCore.pbobjc.m',
      'FirebaseMessaging/FirebaseMessaging/Sources/Protos/GtalkExtensions.pbobjc.m',
    ].each do |firebase_proto_path|
      absolute_proto_path = File.join(installer.sandbox.root, firebase_proto_path)
      next unless File.exist?(absolute_proto_path)

      firebase_proto_source = File.read(absolute_proto_path)
      next if firebase_proto_source.include?('#import <libkern/OSAtomic.h>')

      firebase_proto_source.sub!('// @@protoc_insertion_point(imports)',
                                 "#import <libkern/OSAtomic.h>\n// @@protoc_insertion_point(imports)")
      File.chmod(0o644, absolute_proto_path)
      File.write(absolute_proto_path, firebase_proto_source)
    end

    gul_session_path = File.join(
      installer.sandbox.root,
      'GoogleUtilities/GoogleUtilities/Network/GULNetworkURLSession.m'
    )
    if File.exist?(gul_session_path)
      gul_session_source = File.read(gul_session_path)
      unless gul_session_source.include?('NSMutableURLRequest *uploadRequest')
        gul_session_source.sub!(
          "  NSURLSession *session;\n  BOOL didWriteFile = NO;\n",
          "  NSURLSession *session;\n  BOOL didWriteFile = NO;\n" \
          "  NSData *requestBody = request.HTTPBody;\n" \
          "  NSMutableURLRequest *uploadRequest = [request mutableCopy];\n" \
          "  uploadRequest.HTTPBody = nil;\n"
        )
      end
      gul_session_source.gsub!(
        "didWriteFile = [request.HTTPBody writeToFile:_uploadingFileURL.path\n" \
        "                                         options:NSDataWritingAtomic\n" \
        "                                           error:&writeError];",
        "didWriteFile = [requestBody writeToFile:_uploadingFileURL.path\n" \
        "                                    options:NSDataWritingAtomic\n" \
        "                                      error:&writeError];"
      )
      gul_session_source.gsub!(
        'postRequestTask = [session uploadTaskWithRequest:request fromFile:_uploadingFileURL];',
        'postRequestTask = [session uploadTaskWithRequest:uploadRequest fromFile:_uploadingFileURL];'
      )
      gul_session_source.gsub!(
        'postRequestTask = [session uploadTaskWithRequest:request fromData:request.HTTPBody];',
        'postRequestTask = [session uploadTaskWithRequest:uploadRequest fromData:requestBody];'
      )
      File.chmod(0o644, gul_session_path)
      File.write(gul_session_path, gul_session_source)
    end

    gdt_uploader_path = File.join(
      installer.sandbox.root,
      'GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m'
    )
    if File.exist?(gdt_uploader_path)
      gdt_uploader_source = File.read(gdt_uploader_path)
      unless gdt_uploader_source.include?('currentTaskUploadData')
        gdt_uploader_source.sub!(
          "/// Redeclared as readwrite.\n" \
          "@property(nullable, nonatomic, readwrite) NSURLSessionUploadTask *currentTask;\n\n" \
          "/// A flag indicating if there is an ongoing upload.",
          "/// Redeclared as readwrite.\n" \
          "@property(nullable, nonatomic, readwrite) NSURLSessionUploadTask *currentTask;\n\n" \
          "/// Data used by the current upload task. Upload requests must not contain a body.\n" \
          "@property(nullable, nonatomic, readwrite) NSData *currentTaskUploadData;\n\n" \
          "/// A flag indicating if there is an ongoing upload."
        )
      end
      gdt_uploader_source.gsub!(
        'NSURLRequest *request = [self constructRequestForTarget:target data:dataToSend];',
        'NSMutableURLRequest *request = [[self constructRequestForTarget:target data:dataToSend] mutableCopy];' \
        "\n    request.HTTPBody = nil;"
      )
      gdt_uploader_source.gsub!(
        "#endif\n    self.currentTask = [self.uploaderSession",
        "#endif\n    self.currentTaskUploadData = dataToSend;\n    self.currentTask = [self.uploaderSession"
      )
      gdt_uploader_source.gsub!(
        "  self.currentTask = nil;\n}",
        "  self.currentTask = nil;\n  self.currentTaskUploadData = nil;\n}"
      )
      gdt_uploader_source.gsub!(
        "NSURLRequest *newRequest = [self constructRequestForTarget:kGDTCORTargetCCT\n" \
        "                                                            data:task.originalRequest.HTTPBody];\n" \
        "      completionHandler(newRequest);",
        "NSMutableURLRequest *newRequest =\n" \
        "          [[self constructRequestForTarget:kGDTCORTargetCCT\n" \
        "                                      data:self.currentTaskUploadData ?: [NSData data]] mutableCopy];\n" \
        "      newRequest.HTTPBody = nil;\n" \
        "      completionHandler(newRequest);"
      )
      File.chmod(0o644, gdt_uploader_path)
      File.write(gdt_uploader_path, gdt_uploader_source)
    end
  end
end

target 'singhamarket-tvOS' do
  target 'singhamarket-tvOSTests' do
    inherit! :search_paths
  end
end
